# Generated by Django 5.0.6 on 2024-06-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_friendrequest_options_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['friend']},
        ),
    ]
