# Generated by Django 5.0.6 on 2024-06-14 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_list', to='chats.chatlist'),
            preserve_default=False,
        ),
    ]
