# Generated by Django 5.0.6 on 2024-06-14 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_message_chat_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlist',
            name='chat_list',
            field=models.ManyToManyField(blank=True, related_name='chat_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
