# Generated by Django 5.0.6 on 2024-06-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chatlist_chat_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat_list',
        ),
        migrations.DeleteModel(
            name='ChatList',
        ),
    ]
