# Generated by Django 5.0.6 on 2024-06-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_message_user_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_receiver',
        ),
    ]
