# Generated by Django 5.0.6 on 2024-07-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
